In [1]:
import math
import numpy as np

In [2]:
import pickle
dbfile = open('extracted_dataset', 'rb')
# source, destination
dataset = pickle.load(dbfile)                     
dbfile.close()

In [3]:
X=np.array(dataset['features'].tolist())
y=np.array(dataset['class'].tolist())

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)
print(classification_report(y_test,y_pred))

[[ 9  1  0  0  0  1  4  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [10  3  0  3  2  5  1  1  0  2]
 [ 3  0  0  5  3  0  7  1  2  1]
 [ 1  0  0  1 10  0  8  0  2  1]
 [ 3  4  0  1  1  6  0  1  2  0]
 [ 0  0  0  0  2  0 18  0  0  0]
 [ 0  0  0  1  2  0  0 18  3  0]
 [ 1  1  0  0  2  1  1  3  6  0]
 [10  1  0  2  0  0  7  4  0  1]]
              precision    recall  f1-score   support

           1       0.24      0.60      0.35        15
           2       0.52      1.00      0.69        11
           3       0.00      0.00      0.00        27
           4       0.38      0.23      0.29        22
           5       0.45      0.43      0.44        23
           6       0.46      0.33      0.39        18
           7       0.39      0.90      0.55        20
           8       0.64      0.75      0.69        24
           9       0.40      0.40      0.40        15
          10       0.20      0.04      0.07        25

    accuracy                           0.42       200
   macro avg       

C:\Users\User\Anaconda\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
import seaborn as sns
sns.heatmap(cf_matrix, annot=True ,cmap='Blues')