In [1]:
import math
import numpy as np

In [2]:
import pickle
dbfile = open('extracted_dataset', 'rb')
# source, destination
dataset = pickle.load(dbfile)                     
dbfile.close()

In [3]:
X=np.array(dataset['features'].tolist())
y=np.array(dataset['class'].tolist())

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
classifier = RandomForestClassifier()

In [8]:
classifier.fit(X_train, y_train)

C:\Users\User\Anaconda\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)
print(classification_report(y_test,y_pred))

[[ 7  1  0  1  0  0  3  0  1  2]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 4  6  2  6  1  7  0  0  1  0]
 [ 1  0  1 14  0  0  1  1  0  4]
 [ 0  1  1  8  6  3  2  0  2  0]
 [ 1  4  1  2  1  6  0  0  1  2]
 [ 1  0  0  1  0  1 17  0  0  0]
 [ 0  0  2  4  6  0  1 10  1  0]
 [ 2  2  0  3  2  0  0  1  5  0]
 [ 4  3  3  9  0  1  0  1  1  3]]
              precision    recall  f1-score   support

           1       0.35      0.47      0.40        15
           2       0.39      1.00      0.56        11
           3       0.20      0.07      0.11        27
           4       0.29      0.64      0.40        22
           5       0.38      0.26      0.31        23
           6       0.33      0.33      0.33        18
           7       0.71      0.85      0.77        20
           8       0.77      0.42      0.54        24
           9       0.42      0.33      0.37        15
          10       0.27      0.12      0.17        25

    accuracy                           0.41       200
   macro avg       

In [11]:
import seaborn as sns
sns.heatmap(cf_matrix, annot=True ,cmap='Blues')