In [1]:
import math
import numpy as np

In [2]:
import pickle
dbfile = open('extracted_dataset', 'rb')
# source, destination
dataset = pickle.load(dbfile)                     
dbfile.close()

In [3]:
X=np.array(dataset['features'].tolist())
y=np.array(dataset['class'].tolist())

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [6]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [7]:
y_pred = svclassifier.predict(X_test)

In [8]:
from sklearn.metrics import classification_report, confusion_matrix
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)
print(classification_report(y_test,y_pred))

[[ 6  0  0  2  0  2  5  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 4  4  1  5  1  8  0  2  1  1]
 [ 1  0  0 11  1  1  6  0  1  1]
 [ 1  1  0  4  7  0  6  0  4  0]
 [ 1  3  0  3  2  6  0  0  3  0]
 [ 0  0  0  1  1  0 18  0  0  0]
 [ 0  0  0  2  1  0  0 19  2  0]
 [ 0  1  0  3  2  1  0  0  8  0]
 [ 7  1  0  6  0  1  6  2  2  0]]
              precision    recall  f1-score   support

           1       0.30      0.40      0.34        15
           2       0.52      1.00      0.69        11
           3       1.00      0.04      0.07        27
           4       0.30      0.50      0.37        22
           5       0.47      0.30      0.37        23
           6       0.32      0.33      0.32        18
           7       0.44      0.90      0.59        20
           8       0.83      0.79      0.81        24
           9       0.38      0.53      0.44        15
          10       0.00      0.00      0.00        25

    accuracy                           0.43       200
   macro avg       

In [9]:
import seaborn as sns
sns.heatmap(cf_matrix, annot=True ,cmap='Blues')